### ISSUE TITLE
User Cannot Add Task Without Selecting BDR

### ISSUE THREAD

**Issue by MarG66** [code4romania/vic#335] opened 2024-07-29 12:25 UTC
**Preconditions:**
The user must be logged in on the "Categorii activitati" page.

**Steps to Reproduce:**
1. Click on the "Adauga Categorie" button
2. Enter valid data into "Denumire activiate" input
3. Click on the "Salveaza modificari" button

**Expected Results:**
3. The task is created without BDR.

**Actual Results:**
3. No action is taken, the BDR fields are seen as mandatory, but no error is displayed.

**Note:**
Can also be reproduced when editing an already existing tasks that does not have the BDR inputs filled.

**Comment by luciatugui** [comment] 2024-07-31 11:45
Duplicate of #272.

**Closed by luciatugui** 2024-07-31 11:45 UTC
Labels: bug :bug:, web-app
