### ISSUE TITLE
[Login] The Create account form keeps opening instead of the authentication screen

### ISSUE THREAD

**Issue by monikozi** [code4romania/vic#233] opened 2023-09-27 19:11 UTC
### Description

Mobile [Login] The Create account form keeps opening instead of the authentication screen

### Test environment

Android

### Preconditions

I created some erroneous accounts as part of another scenario [#232](https://github.com/code4romania/teo/issues/232)

### Test Data

n/a

### Steps of Reproduction

I used Close all apps. 
I tried opening the TEO app again

### Expected Result

Expected result: once killed, the app to restart on the main login screen

### Actual Result

Actual result: TEO keeps returning the **Creare cont > Date utilizator** form

### Notes (optional)

I used Clear cache and force stop from the Apps settings and Sign in with Google still returns the Date utilizator form

### Screenshots (optional)

https://github.com/code4romania/teo/assets/64305252/cf03a187-6b5f-4a1e-9220-126da2506345

**Comment by birloiflorian** [comment] 2023-11-09 13:57
Remove the "back" button, and add Logout button top-right to remove the token.

**Comment by andrei-manda** [comment] 2024-07-11 13:28
TBD: @radulescuandrew @birloiflorian 
From my point of view this behavior is normal because the process isn't finished

**Comment by radulescuandrew** [comment] 2024-07-16 08:04
@andrei-manda Correct. 

@mirunaioana-msc This is the intended behaviour. Once you authenticated with Cognito, using any provider (user pass or federated) will must complete your account data. In the above situation, the user already logged in with Google, so Google cached the auth data and the backend will always ask to complete the data. 

Also, for the moment the authentication with Google/Facebook/Apple is disabled. 

Please close the issue or advise.

**Closed** 2024-10-11 07:57 UTC
Labels: bug :bug:, high-priority :fire:, invalid, mobile-app
